## 张量的where sort 操作和统计函数

### 1. 张量的 where 函数

In [4]:
import numpy as np

nd1 = np.array([1, 2, 3, 4, 5, 6])
nd2 = np.array([10, 20, 30, 40, 50, 60])
display(nd1, nd2)

array([1, 2, 3, 4, 5, 6])

array([10, 20, 30, 40, 50, 60])

In [5]:
# where函数 如果 True 返回 nd1 中元素; False 返回 nd2 中的元素
cond = np.array([True, False, True, True, False, False])
np.where(cond, nd1, nd2)

array([ 1, 20,  3,  4, 50, 60])

In [6]:
a = np.random.randint(0, 100, size = 50)
a

array([27, 53, 31, 39, 99, 30, 82, 24, 13,  4, 54, 26,  9, 35, 72, 82, 28,
       11, 96, 77, 79, 38, 91, 28, 66,  7, 37, 43, 28, 14, 85, 47, 61, 84,
       12, 34, 80, 76, 84, 58,  7, 35, 32, 29, 31, 96, 67, 83, 92, 28])

In [10]:
# where 函数; 大于50 则展示a中的数据; 否则展示a+20; 后面的随便填写就OK了
np.where(a > 50, a, a+20)

array([47, 53, 51, 59, 99, 50, 82, 44, 33, 24, 54, 46, 29, 55, 72, 82, 48,
       31, 96, 77, 79, 58, 91, 48, 66, 27, 57, 63, 48, 34, 85, 67, 61, 84,
       32, 54, 80, 76, 84, 58, 27, 55, 52, 49, 51, 96, 67, 83, 92, 48])

In [12]:
a = np.random.randint(0, 100, size = 50)
# 从小到大进行排序; 没有输出, 就是改的原始数据
a.sort() 
a

array([ 0,  5,  6,  8,  9, 12, 13, 14, 17, 18, 20, 23, 26, 30, 30, 31, 32,
       36, 43, 44, 44, 44, 44, 47, 49, 50, 52, 53, 54, 56, 60, 62, 63, 63,
       69, 69, 69, 71, 72, 73, 76, 78, 81, 84, 86, 93, 94, 96, 98, 99])

In [13]:
cond = (a > 50) & (a < 60)
np.where(cond, a + 10, a)

array([ 0,  5,  6,  8,  9, 12, 13, 14, 17, 18, 20, 23, 26, 30, 30, 31, 32,
       36, 43, 44, 44, 44, 44, 47, 49, 50, 62, 63, 64, 66, 60, 62, 63, 63,
       69, 69, 69, 71, 72, 73, 76, 78, 81, 84, 86, 93, 94, 96, 98, 99])

### 2. sort 和 argsort 函数

In [27]:
a = np.random.randint(0, 100, size = 50)
a
# 获取排序后 原始数据的下标 张量
index = a.argsort()
index
# 根据花式索引 根据下标 index 获取 从小到大的数据
a[index]

# 根据花式索引获取 从大到小的数据; 两种获取方式
display(a[index][::-1], a[index[::-1]])

array([99, 98, 97, 96, 88, 87, 86, 84, 84, 82, 75, 74, 70, 69, 67, 64, 59,
       59, 59, 55, 54, 49, 48, 47, 43, 43, 41, 37, 35, 34, 32, 27, 27, 25,
       22, 22, 16, 15, 13, 11, 10,  9,  9,  8,  8,  8,  7,  6,  5,  1])

array([99, 98, 97, 96, 88, 87, 86, 84, 84, 82, 75, 74, 70, 69, 67, 64, 59,
       59, 59, 55, 54, 49, 48, 47, 43, 43, 41, 37, 35, 34, 32, 27, 27, 25,
       22, 22, 16, 15, 13, 11, 10,  9,  9,  8,  8,  8,  7,  6,  5,  1])

### 3. 集合操作函数

In [32]:
a = np.random.randint(0, 100, size = 30)
b = np.random.randint(0, 100, size = 30)

display(a, b)
# 交集
display(np.intersect1d(a, b))
# 并集
display(np.union1d(a, b))
# 差集
display(np.setdiff1d(a, b))

array([32, 98, 85, 63, 90, 23, 85, 39, 72, 71, 28, 36, 68, 88, 22, 71, 47,
       24,  7, 28, 66, 25,  7, 81, 21, 59, 32,  8, 36, 57])

array([61, 74, 51, 61, 36, 22, 62, 48, 33, 87, 68, 40, 18, 36, 17, 92, 80,
       84, 51, 86, 67, 91, 46, 96, 73, 84, 62,  9, 32, 55])

array([22, 32, 36, 68])

array([ 7,  8,  9, 17, 18, 21, 22, 23, 24, 25, 28, 32, 33, 36, 39, 40, 46,
       47, 48, 51, 55, 57, 59, 61, 62, 63, 66, 67, 68, 71, 72, 73, 74, 80,
       81, 84, 85, 86, 87, 88, 90, 91, 92, 96, 98])

array([ 7,  8, 21, 23, 24, 25, 28, 39, 47, 57, 59, 63, 66, 71, 72, 81, 85,
       88, 90, 98])

### 4. 数据和统计或汇总函数

min、max、mean、median、sum、std、var、cumsum、cumprod、argmin、argmax、argwhere、cov、corrcoef

In [47]:
a = np.random.randint(1, 100, size = (3, 5))
a

array([[22, 19,  6, 26, 90],
       [38,  7,  9, 49, 33],
       [ 8, 65, 19, 98, 53]])

In [48]:
# 取出张量中的最小值
a.min()

6

In [49]:
# 取出张量中的最大值
a.max()

98

In [50]:
# 使用 水平方向 还是 垂直方向 上计算 使用 axis
a.max(axis = 0)

array([38, 65, 19, 98, 90])

In [51]:
a.max(axis = 1)

array([90, 49, 98])

In [52]:
# 平均值
a.mean()

36.13333333333333

In [53]:
# 中位数
np.median(a)

26.0

In [54]:
# 求和
a.sum()

542

In [55]:
# 标准差; 标准差的平方就是 方差
a.std()

28.518687830185236

In [56]:
# 方差； 方差开平方就是 标准差; 方差越大说明波动越大
a.var()

813.3155555555554

In [60]:
# 给一个 比较简单的数组 看下 下面的 累加和操作 累乘和操作
b = np.array([1, 2, 3, 4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [61]:
# 累加和
b.cumsum()

array([ 1,  3,  6, 10, 15, 21])

In [62]:
# 累乘和
b.cumprod()

array([  1,   2,   6,  24, 120, 720])

In [63]:
# 返回最小值的 索引
b.argmin()

0

In [64]:
# 返回最大值的 索引
b.argmax()

5

In [85]:
a = np.random.randint(10, 100, size = (3, 5))
a

array([[68, 61, 16, 16, 39],
       [62, 99, 19, 47, 27],
       [25, 39, 45, 92, 94]])

In [92]:
# 返回 符合条件的 索引
index = np.argwhere(a > 40)

In [95]:
for i,j in index:
    print(a[i, j])

68
61
62
99
47
45
92
94


In [96]:
# 协方差 (两个属性之间进行计算) 方差: （数据内部, 属性内部计算)
# 举例: 一个男人的受欢迎程度 和 一个男人的语言表达水平有多大的关系
np.cov(a)

array([[ 594.5 ,  551.  , -465.75],
       [ 551.  , 1010.2 , -464.5 ],
       [-465.75, -464.5 , 1016.5 ]])

In [97]:
# 相关性系数; 和协方差有关 0:无关 1:
np.corrcoef(a)

array([[ 1.        ,  0.71100391, -0.599133  ],
       [ 0.71100391,  1.        , -0.45838283],
       [-0.599133  , -0.45838283,  1.        ]])