## 线性代数 张量计算

In [1]:
import numpy as np

a = np.random.randint(1, 10, size = (3, 3))
b = np.random.randint(1, 10, size = (3, 4))

np.matmul(a, b)

array([[ 40,  58,  45,  43],
       [ 55,  73,  72,  67],
       [ 69,  69, 105, 100]])

In [2]:
a @ b

array([[ 40,  58,  45,  43],
       [ 55,  73,  72,  67],
       [ 69,  69, 105, 100]])

In [3]:
a.dot(b)

array([[ 40,  58,  45,  43],
       [ 55,  73,  72,  67],
       [ 69,  69, 105, 100]])

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 