## 索引和切片

### 1. 索引和切片基础知识

In [1]:
import numpy as np

a = np.random.randint(1, 100, size = 10)
a

array([92, 92, 27, 78, 65, 49, 76, 94, 58, 72])

In [2]:
# 获取一个元素
a[3]

78

In [3]:
# 获取多个元素; 目前标准就是 [里面填写下标； 多个用逗号分割]
a[[1, 3, 5]]

array([92, 78, 49])

In [4]:
# 切片；一刀切下去得到一块东西的感觉 类似于 substring的感觉; 左闭右开; 0表示开始下标; 3表示一共获取几个元素
a[0:3]

array([92, 92, 27])

In [5]:
# 切片; 如果冒号前不写, 默认是从0开始； 冒号后面不写则默认 从开始元素到最后一个元素的个数
a[:3]

array([92, 92, 27])

In [6]:
# 切片; 如果冒号前不写, 默认是从0开始； 冒号后面不写则默认 从开始元素到最后一个元素的个数
a[5:]

array([49, 76, 94, 58, 72])

In [7]:
# 从某个索引开始获取
a[5:9]

array([49, 76, 94, 58])

In [8]:
# 为了方便查看 打印一下 a
a

array([92, 92, 27, 78, 65, 49, 76, 94, 58, 72])

In [9]:
# 从索引 = 0开始 每2个当中获取一个
a[::2]

array([92, 27, 65, 76, 58])

In [10]:
# 从索引 = 3开始 每3个取一个
a[3::3]

array([78, 76, 72])

In [11]:
# 数组 前后下标翻转; [意思为 从后往前选择]
a[::-1]

array([72, 58, 94, 76, 49, 65, 78, 27, 92, 92])

In [12]:
# 数组 前后下标翻转; [意思为 从后往前选择] 两个里面取一个
a[::-2]

array([72, 94, 49, 78, 92])

In [13]:
# 数组
a[5::-3]

array([49, 27])

In [14]:
# 打印一下数组方便查看
a

array([92, 92, 27, 78, 65, 49, 76, 94, 58, 72])

In [15]:
# 索引从1开始到7结束; 每隔2个取一个 [正向获取 位置3>0; 位置1<位置2] [反向获取 位置3<0; 位置1 > 位置2]
a[1:7:2]

array([92, 78, 49])

In [17]:
a[5:2:-1]

array([49, 65, 78])

### 2. 多维张量的切片

In [18]:
b = np.random.randint(0, 30, size = (10, 5))
b

array([[23,  2,  5, 28, 10],
       [26, 28, 24, 28, 14],
       [22, 29, 13, 10,  0],
       [22,  2, 15, 14, 19],
       [ 1, 25, 18, 20,  7],
       [21, 25, 22, 24, 28],
       [ 7, 10,  1, 29,  7],
       [14, 13, 27, 22, 28],
       [25, 16, 16, 11,  5],
       [26, 23, 19,  9, 24]])

In [20]:
# 多维张量切片; 获取整行
b[1]

array([26, 28, 24, 28, 14])

In [21]:
# 多维张量取 多行
b[[1, 3, 5]]

array([[26, 28, 24, 28, 14],
       [22,  2, 15, 14, 19],
       [21, 25, 22, 24, 28]])

In [22]:
# 取固定纬度的值; 用逗号分隔纬度 行=1 列=3
b[1, 3]

28

In [23]:
# 取一行中多个列的值 行=1, 列=[1,2,3]
b[1,[1,2,3]]

array([28, 24, 28])

In [28]:
# 取多行 多列的数据
b[2::7]

array([[22, 29, 13, 10,  0],
       [26, 23, 19,  9, 24]])

In [29]:
# 取多行 多列的数据; 行从2到最后每隔7个 取一个; 列从1到最后 每隔3个取一个
b[2::7, 1::3]

array([[29,  0],
       [23, 24]])

In [30]:
# 取最后一个元素; -1表示倒着数
b[-1, -1]

24

In [32]:
# 获取倒着数 一行数据 写法 和 b[-2, [-1,-2,-3]] 一样 
b[-2, (-1,-2,-3)]

array([ 5, 11, 16])

### 3. 花式索引和索引技巧

In [34]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
# 切片时 不是深拷贝; 公用一份数据
b = a[3:7]
b

array([100,   4,   5,   6])

In [40]:
b[0] = 100
display(a, b)

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

array([100,   4,   5,   6])

In [42]:
a.flags.owndata

True

In [43]:
b.flags.owndata

False

In [50]:
a = np.arange(20, 100, 10)
a

array([20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
# 在填写索引的时候给了一个数组; 这种索引就是花式索引; 花式索引返回的数据 都是经过深拷贝的数据;独立于原始数据的新数据
b = a[[1, 3]]
b

array([30, 50])

In [52]:
b.flags.owndata

True

In [80]:
a = np.random.randint(0, 151, size = (100, 3))
a

array([[143,  53, 144],
       [ 94,  64,  28],
       [ 21,  71, 142],
       [123, 150, 137],
       [130, 125, 116],
       [ 84,  76,  49],
       [107,  41, 111],
       [100,   3,  27],
       [ 56, 117, 109],
       [ 67,   5,  46],
       [ 65, 120,  44],
       [146,  65,  39],
       [ 22, 137,  85],
       [ 71, 114, 132],
       [ 97,  25, 130],
       [ 37, 144,  37],
       [ 92,  86, 137],
       [ 91,   8,  95],
       [115,  88,  20],
       [ 25,  22,  32],
       [127,  53,  96],
       [ 59,  52,  44],
       [ 81, 109,  71],
       [ 75, 114,  63],
       [139,  57,  40],
       [ 24,  91,   0],
       [113,  15, 110],
       [  4,  15,  72],
       [  3,  49,   9],
       [ 85,  39,  52],
       [ 27,  45, 103],
       [ 30, 107,  50],
       [ 38, 114,  50],
       [ 71, 103, 120],
       [142, 125,  77],
       [ 23,  88,  10],
       [114,   4,  73],
       [ 36,  50,  65],
       [ 16,  84, 116],
       [ 40,  45,  72],
       [136, 130,  14],
       [ 50, 133

In [81]:
# 筛选出所有 元素>120 的元素
cond = a >= 120

In [82]:
a[cond]

array([143, 144, 142, 123, 150, 137, 130, 125, 120, 146, 137, 132, 130,
       144, 137, 127, 139, 120, 142, 125, 136, 130, 133, 137, 146, 131,
       137, 141, 138, 136, 124, 127, 138, 141, 150, 135, 149, 137, 150,
       126, 149, 126, 128, 142, 145, 128, 133, 122, 140, 128, 138, 128,
       144, 144, 135, 146, 148, 147, 129, 148, 128, 147, 132, 131])

In [83]:
# 筛选出 每个列都 > 120的
cond2 = cond[:,0] * cond[:,1] * cond[:,2]

In [84]:
a[cond2]

array([[123, 150, 137]])

In [87]:
# 筛选出 一行中都>100 或者 一行中都<30
cond1 = a>100
cond2 = a<30
display(a[cond1[:, 0]*cond1[:, 1]*cond1[:, 2]], a[cond2[:, 0]*cond1[:, 1]*cond1[:, 2]])

array([[123, 150, 137],
       [130, 125, 116],
       [115, 137, 146],
       [101, 136, 124],
       [141, 150, 104],
       [107, 108, 128]])

array([], shape=(0, 3), dtype=int64)