## 复制和视图

### 1. 完全没有复制; 对同一份数据进行操作

In [1]:
import numpy as np

nd1 = np.random.randint(1, 10, size = 3)
nd1 

array([3, 8, 7])

In [2]:
nd2 = nd1

In [3]:
nd2 is nd1

True

### 2. 视图操作；叫法比较多 视图 或 查看 或 浅拷贝

In [5]:
a = np.random.randint(1, 100, size = 5)
b = a.view()
display(a, b)

array([83, 98, 54, 12,  8])

array([83, 98, 54, 12,  8])

In [7]:
# 证明 a 和 b 不是一回事
a is b

False

In [10]:
# 查看 a 是否拥有自己的数据
a.flags.owndata

True

In [9]:
# 查看 b 是否拥有自己的数据; 使用的数据还是 a 的数据
b.flags.owndata

False

In [16]:
a[0] = 1024
b[0] = 1
display(a, b)
a is b

array([1024,    4,    6,    8,    6])

array([1, 4, 6, 8, 6])

False

### 3. 深拷贝

In [14]:
a = np.random.randint(1, 10, size = 5)
b = a.copy()
display(a, b)

array([5, 4, 6, 8, 6])

array([5, 4, 6, 8, 6])

In [15]:
# 深copy 含义: 完全复制一份自己的数据
a is b

False

In [18]:
a[0] = 1024
b[0] = 2048
display(a, b)

array([1024,    4,    6,    8,    6])

array([2048,    4,    6,    8,    6])

In [29]:
# 那么 copy() 方法如何使用呢?
a = np.arange(1e8)
a

array([0.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 9.9999997e+07,
       9.9999998e+07, 9.9999999e+07])

In [30]:
# a的数据非常大, 只使用其中的一部分；复制出来后, 删除掉可以省很多内存
b = a[[1, 2, 4]].copy()
b

array([1., 2., 4.])

In [31]:
del a

In [32]:
a

NameError: name 'a' is not defined