## 基本操作

### 1. 数组的创建

In [4]:
import numpy as np

# 创建一个数组
l = [1, 2, 3, 4, 5]
nd1 = np.array(l) # 输入 arr + tab 键可以自动补全
print(nd1)
display(nd1)

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [3]:
nd2 = np.zeros(shape = (3, 4), dtype = np.int32)
nd2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [5]:
nd3 = np.ones(shape=(3, 4), dtype=np.float32)
nd3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [6]:
nd4 = np.full(shape= (2, 3, 4), fill_value=3.1415926) # 生成任意形状的 数组
nd4

array([[[3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926]],

       [[3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926]]])

In [34]:
nd5 = np.random.randint(0, 100, size = 15) # 生成 0 到 100 之间的一个 长度为 20的数组
nd5

array([24, 52, 14,  3, 14, 44, 73, 20, 14, 87,  5, 80, 74, 98, 76])

In [9]:
nd6  = np.random.rand(2, 3) # 生成 2行3列的 数组; 填充值为 0到1
nd6

array([[0.47492402, 0.37454301, 0.58271759],
       [0.93521117, 0.8467993 , 0.30683502]])

In [28]:
nd7 = np.random.randn(3, 5) # 生成一个 正态分布 数组; 所有数的 理论上的平均值为 0 标准差为1
nd7

array([[-1.55637457,  0.14516802,  1.62660057,  0.96620436,  0.96427047],
       [ 0.1087439 ,  0.33462219, -1.19142785, -0.48769286,  2.18119894],
       [ 0.40822891, -0.43723245,  0.45958965, -1.50829561, -0.46922298]])

In [29]:
nd8 = np.random.normal(loc = 100, scale = 10, size = (1, 5)) # 生成一个 1行5列的 正态分布；平均值为 100，标准差为 10
nd8

array([[ 88.98562362,  85.80364403, 105.03156046, 113.14545894,
        111.49479694]])

In [9]:
nd9 = np.arange(1, 100) # 等差数列 差值为1；1 到 100 的一个一维数组
nd9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
nd91 = np.arange(1, 100, step = 10) # 等差数列 差值为 10; 左闭右开 的一个等差数列
nd91

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [32]:
nd10 = np.linspace(1, 100, num = 10) # 等差数列 差值为 10; 左闭右闭 的一个等差数列；数字个数为 10 个
nd10

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

### 2. 查看数组的属性

In [1]:
import numpy as np

nd = np.random.randn(2, 3)
nd

array([[ 2.13935459, -0.47464868,  0.14782514],
       [-0.3599204 , -0.30391272,  1.19371069]])

In [2]:
# 查看数组的形状
nd.shape

(2, 3)

In [3]:
# 查看数组的数据类型
nd.dtype

dtype('float64')

In [5]:
# 查看数组中的 数据个数
nd.size

6

In [7]:
# 查看数组的纬度
nd.ndim

2

In [8]:
# 查看每个元素占用的字节数
nd.itemsize

8

### 3. 文件操作

In [20]:
import numpy as np

nd1 = np.random.randint(0, 10, size=5)
nd2 = np.random.randn(2, 4)
display(nd1, nd2)

array([1, 0, 7, 4, 8])

array([[-0.08732392,  0.57593144, -0.50933302, -0.3771902 ],
       [ 0.69635882,  0.83538496,  0.80282254,  0.427012  ]])

In [17]:
# 把 单个数组数据保存到文件中; 只保存路径就可以了, 文件自动保存为 后缀为 .npy 的文件
np.save('./data', nd2)

In [18]:
# 加载 单个文件数据
np.load('./data.npy') 

array([[ 0.60789876,  0.85777746, -1.43031209, -0.76408594],
       [-0.38624456, -0.77851281, -2.00390671, -0.01413194]])

In [19]:
# 把多个文件 保存在一个文件中; a, b 等我们称之为 key
np.savez('./data', a = nd1, b = nd2)

In [37]:
# 加载 单个文件数据; 数据获取必须 要加上 key
data = np.load('./data.npz')
data

NpzFile './data.npz' with keys: a, b

In [34]:
# 加载 单个文件数据; 数据获取必须 要加上 key
data['a']

array([2, 1, 2, 8, 6])

In [35]:
# 加载 单个文件数据; 数据获取必须 要加上 key
data['b']

array([[ 0.60789876,  0.85777746, -1.43031209, -0.76408594],
       [-0.38624456, -0.77851281, -2.00390671, -0.01413194]])

In [ ]:
# 如果获取的不是 数据中有的key 直接报错
data['wwww']

In [38]:
# 保存压缩文件
np.savez_compressed('./data2.npz', x = nd1, y = nd2)

In [10]:
data2 = np.load('./data2.npz')
data2

NpzFile './data2.npz' with keys: x, y

In [11]:
data2['x']

array([2, 1, 2, 8, 6])

In [12]:
data2['y']

array([[ 0.60789876,  0.85777746, -1.43031209, -0.76408594],
       [-0.38624456, -0.77851281, -2.00390671, -0.01413194]])

In [36]:
# 保存 txt 文件
np.savetxt(fname= './data.txt', X = nd1, fmt='%0.2f', delimiter=',')

In [37]:
np.loadtxt('./data.txt')

array([1., 0., 7., 4., 8.])

In [38]:
# 保存 csv 文件
np.savetxt(fname='./data.csv', X = nd1, fmt='%d', delimiter=';')

In [39]:
np.loadtxt('./data.csv')

array([1., 0., 7., 4., 8.])