## 数组的变形、转置相关操作

### 1. 数组的变形

In [1]:
import numpy as np

a = np.arange(10, 100, 2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [2]:
a.size

45

In [3]:
# 是浅拷贝; 共用一份数据
b = a.reshape(9, 5)
b

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [4]:
b[0][0] = 100
b

array([[100,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98]])

In [5]:
a

array([100,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98])

### 2. 数组的转置

In [15]:
a = np.random.randint(0, 100, size = (10, 3))
a

array([[21,  9, 27],
       [50, 58, 94],
       [ 9, 33,  7],
       [82, 48, 73],
       [87, 72, 28],
       [73, 86, 64],
       [44, 78, 68],
       [88, 27, 52],
       [36,  9, 13],
       [27, 28, 16]])

In [16]:
# 张量的转置; 或者用 np.transpose 方法
#a.T
a.transpose()

array([[21, 50,  9, 82, 87, 73, 44, 88, 36, 27],
       [ 9, 58, 33, 48, 72, 86, 78, 27,  9, 28],
       [27, 94,  7, 73, 28, 64, 68, 52, 13, 16]])

In [17]:
a

array([[21,  9, 27],
       [50, 58, 94],
       [ 9, 33,  7],
       [82, 48, 73],
       [87, 72, 28],
       [73, 86, 64],
       [44, 78, 68],
       [88, 27, 52],
       [36,  9, 13],
       [27, 28, 16]])

In [20]:
np.transpose(a, (1, 0))

array([[21, 50,  9, 82, 87, 73, 44, 88, 36, 27],
       [ 9, 58, 33, 48, 72, 86, 78, 27,  9, 28],
       [27, 94,  7, 73, 28, 64, 68, 52, 13, 16]])

In [21]:
b = np.random.randint(0, 10, size = (3, 5, 7))
b.shape

(3, 5, 7)

### 3. 数组的堆叠

In [39]:
a = np.random.randint(0, 10, size = (3, 5))
b = np.random.randint(0, 10, size = (3, 5))

# 增加行的操作; 默认合并 行增加 axis 有轴的意思; 0:表示横向或水平方向 上堆叠 为默认值; 1:表示 垂直方向上 堆叠
np.concatenate((a, b), axis = 1)

array([[9, 7, 9, 6, 5, 2, 8, 5, 6, 6],
       [6, 2, 8, 8, 4, 2, 3, 3, 2, 9],
       [4, 0, 6, 3, 3, 0, 5, 7, 9, 3]])

In [27]:
# 水平方向上进行堆叠；列增加
np.hstack((a, b))

array([[2, 7, 3, 0, 5, 0, 6, 8, 3, 5],
       [0, 2, 1, 1, 6, 2, 5, 9, 5, 1],
       [6, 3, 3, 1, 1, 1, 0, 1, 1, 5]])

In [28]:
# 垂直方向上进行堆叠；行增加
np.vstack((a, b))

array([[2, 7, 3, 0, 5],
       [0, 2, 1, 1, 6],
       [6, 3, 3, 1, 1],
       [0, 6, 8, 3, 5],
       [2, 5, 9, 5, 1],
       [1, 0, 1, 1, 5]])

In [29]:
np.vstack((a,a,b))

array([[2, 7, 3, 0, 5],
       [0, 2, 1, 1, 6],
       [6, 3, 3, 1, 1],
       [2, 7, 3, 0, 5],
       [0, 2, 1, 1, 6],
       [6, 3, 3, 1, 1],
       [0, 6, 8, 3, 5],
       [2, 5, 9, 5, 1],
       [1, 0, 1, 1, 5]])

### 4. 数组的拆分

In [30]:
a = np.random.randint(0, 100, size = (15, 10))
a

array([[67, 44, 38, 44,  6, 38, 85, 90, 13, 11],
       [57, 13, 61, 85, 62,  4, 88, 91, 18, 86],
       [23, 62, 66, 12, 71, 53, 22, 94, 26, 94],
       [56, 37, 29, 44, 82, 59, 68,  0, 25, 54],
       [ 4, 80, 60, 67, 48, 46, 91, 98, 91, 29],
       [52,  6, 49, 42, 18, 11, 36,  4, 63, 62],
       [26, 25, 69, 18, 40, 30, 49, 19,  5, 78],
       [28, 17, 62, 51, 25,  8, 26, 40, 29, 59],
       [56, 92, 13, 83, 29, 29, 17, 42, 84,  4],
       [14, 98, 86, 20, 79, 64, 74, 43, 52, 22],
       [28, 46, 51,  6, 16, 64, 62, 86, 85, 26],
       [65, 43, 91, 60, 58, 23, 44, 43, 62, 81],
       [ 5, 68, 50, 43, 16, 55, 24, 80,  5, 42],
       [65, 36, 41, 27, 73, 76, 10, 80, 83, 32],
       [31, 63,  0, 27,  9, 82, 92, 28,  5, 39]])

In [32]:
# 如果第二个必填参数为数字; 则表示行 平均分成几份
np.split(a, indices_or_sections=3)

[array([[67, 44, 38, 44,  6, 38, 85, 90, 13, 11],
        [57, 13, 61, 85, 62,  4, 88, 91, 18, 86],
        [23, 62, 66, 12, 71, 53, 22, 94, 26, 94],
        [56, 37, 29, 44, 82, 59, 68,  0, 25, 54],
        [ 4, 80, 60, 67, 48, 46, 91, 98, 91, 29]]),
 array([[52,  6, 49, 42, 18, 11, 36,  4, 63, 62],
        [26, 25, 69, 18, 40, 30, 49, 19,  5, 78],
        [28, 17, 62, 51, 25,  8, 26, 40, 29, 59],
        [56, 92, 13, 83, 29, 29, 17, 42, 84,  4],
        [14, 98, 86, 20, 79, 64, 74, 43, 52, 22]]),
 array([[28, 46, 51,  6, 16, 64, 62, 86, 85, 26],
        [65, 43, 91, 60, 58, 23, 44, 43, 62, 81],
        [ 5, 68, 50, 43, 16, 55, 24, 80,  5, 42],
        [65, 36, 41, 27, 73, 76, 10, 80, 83, 32],
        [31, 63,  0, 27,  9, 82, 92, 28,  5, 39]])]

In [33]:
np.split(a, indices_or_sections=2, axis=1)

[array([[67, 44, 38, 44,  6],
        [57, 13, 61, 85, 62],
        [23, 62, 66, 12, 71],
        [56, 37, 29, 44, 82],
        [ 4, 80, 60, 67, 48],
        [52,  6, 49, 42, 18],
        [26, 25, 69, 18, 40],
        [28, 17, 62, 51, 25],
        [56, 92, 13, 83, 29],
        [14, 98, 86, 20, 79],
        [28, 46, 51,  6, 16],
        [65, 43, 91, 60, 58],
        [ 5, 68, 50, 43, 16],
        [65, 36, 41, 27, 73],
        [31, 63,  0, 27,  9]]),
 array([[38, 85, 90, 13, 11],
        [ 4, 88, 91, 18, 86],
        [53, 22, 94, 26, 94],
        [59, 68,  0, 25, 54],
        [46, 91, 98, 91, 29],
        [11, 36,  4, 63, 62],
        [30, 49, 19,  5, 78],
        [ 8, 26, 40, 29, 59],
        [29, 17, 42, 84,  4],
        [64, 74, 43, 52, 22],
        [64, 62, 86, 85, 26],
        [23, 44, 43, 62, 81],
        [55, 24, 80,  5, 42],
        [76, 10, 80, 83, 32],
        [82, 92, 28,  5, 39]])]

In [34]:
# 如果indices_or_sections 给出一个数组; 这里会按照具体的点进行切分
np.split(a, indices_or_sections=[1, 3, 7, 9])

[array([[67, 44, 38, 44,  6, 38, 85, 90, 13, 11]]),
 array([[57, 13, 61, 85, 62,  4, 88, 91, 18, 86],
        [23, 62, 66, 12, 71, 53, 22, 94, 26, 94]]),
 array([[56, 37, 29, 44, 82, 59, 68,  0, 25, 54],
        [ 4, 80, 60, 67, 48, 46, 91, 98, 91, 29],
        [52,  6, 49, 42, 18, 11, 36,  4, 63, 62],
        [26, 25, 69, 18, 40, 30, 49, 19,  5, 78]]),
 array([[28, 17, 62, 51, 25,  8, 26, 40, 29, 59],
        [56, 92, 13, 83, 29, 29, 17, 42, 84,  4]]),
 array([[14, 98, 86, 20, 79, 64, 74, 43, 52, 22],
        [28, 46, 51,  6, 16, 64, 62, 86, 85, 26],
        [65, 43, 91, 60, 58, 23, 44, 43, 62, 81],
        [ 5, 68, 50, 43, 16, 55, 24, 80,  5, 42],
        [65, 36, 41, 27, 73, 76, 10, 80, 83, 32],
        [31, 63,  0, 27,  9, 82, 92, 28,  5, 39]])]

In [36]:
# 有水平堆叠和垂直堆叠; 就有 水平方向拆分和垂直方向上拆分
np.hsplit(a, indices_or_sections=2)

[array([[67, 44, 38, 44,  6],
        [57, 13, 61, 85, 62],
        [23, 62, 66, 12, 71],
        [56, 37, 29, 44, 82],
        [ 4, 80, 60, 67, 48],
        [52,  6, 49, 42, 18],
        [26, 25, 69, 18, 40],
        [28, 17, 62, 51, 25],
        [56, 92, 13, 83, 29],
        [14, 98, 86, 20, 79],
        [28, 46, 51,  6, 16],
        [65, 43, 91, 60, 58],
        [ 5, 68, 50, 43, 16],
        [65, 36, 41, 27, 73],
        [31, 63,  0, 27,  9]]),
 array([[38, 85, 90, 13, 11],
        [ 4, 88, 91, 18, 86],
        [53, 22, 94, 26, 94],
        [59, 68,  0, 25, 54],
        [46, 91, 98, 91, 29],
        [11, 36,  4, 63, 62],
        [30, 49, 19,  5, 78],
        [ 8, 26, 40, 29, 59],
        [29, 17, 42, 84,  4],
        [64, 74, 43, 52, 22],
        [64, 62, 86, 85, 26],
        [23, 44, 43, 62, 81],
        [55, 24, 80,  5, 42],
        [76, 10, 80, 83, 32],
        [82, 92, 28,  5, 39]])]

In [38]:
np.vsplit(a, indices_or_sections=[5])

[array([[67, 44, 38, 44,  6, 38, 85, 90, 13, 11],
        [57, 13, 61, 85, 62,  4, 88, 91, 18, 86],
        [23, 62, 66, 12, 71, 53, 22, 94, 26, 94],
        [56, 37, 29, 44, 82, 59, 68,  0, 25, 54],
        [ 4, 80, 60, 67, 48, 46, 91, 98, 91, 29]]),
 array([[52,  6, 49, 42, 18, 11, 36,  4, 63, 62],
        [26, 25, 69, 18, 40, 30, 49, 19,  5, 78],
        [28, 17, 62, 51, 25,  8, 26, 40, 29, 59],
        [56, 92, 13, 83, 29, 29, 17, 42, 84,  4],
        [14, 98, 86, 20, 79, 64, 74, 43, 52, 22],
        [28, 46, 51,  6, 16, 64, 62, 86, 85, 26],
        [65, 43, 91, 60, 58, 23, 44, 43, 62, 81],
        [ 5, 68, 50, 43, 16, 55, 24, 80,  5, 42],
        [65, 36, 41, 27, 73, 76, 10, 80, 83, 32],
        [31, 63,  0, 27,  9, 82, 92, 28,  5, 39]])]