## 张量的广播机制

In [1]:
import numpy as np

a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [2]:
b = a.reshape(4, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
arr1 = np.array([0, 1, 2, 3] * 3)
arr1.sort()
arr1 = arr1.reshape(4, 3)
arr2 = np.array([1, 2, 3])
display(arr1, arr2)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([1, 2, 3])

In [10]:
# arr1 和 arr2 虽然形状不一样, 仍然能够进行计算, 这是 numpy 对张量进行了广播所致; 行不够 广播行
arr1 + arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [13]:
# arr1 和 arr3 虽然形状不一样, 仍然能够计算, 列不够, 广播列
arr3 = np.array([[1], [2], [3], [4]])
arr3

array([[1],
       [2],
       [3],
       [4]])

In [16]:
arr1 + arr3

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

In [15]:
display(arr1.shape, arr3.shape)

(4, 3)

(4, 1)

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8] * 3).reshape(3, 4, 2)
a

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [23]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7]).reshape(4, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
a + b

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15]],

       [[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15]],

       [[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15]]])