## 数据类型

### 1. 常用数据类型

int8, int16, int32, int64 ..., uint8 无符号

float16, float32, float64 ...

str字符串类型

int8 表示能存储 256个有符号的 数字; -128到127 之间的数字

uint8表示能存储 256个无符号的 数字; 0到255 之间的数字

In [3]:
import numpy as np

# 创建一个数组
nd1 = np.array([2, 3], dtype=np.int8)
display(nd1)

array([2, 3], dtype=int8)

In [4]:
# 注意下 类型能够包含的数字 最大和最小都是多少; 这块需要了解一下
np.array([-3, -5, 0, 255, 0, 256], dtype = np.uint8)

/var/folders/_x/7v1hghg91r37__pjl_6c64sm0000gn/T/ipykernel_63757/795138074.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -3 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([-3, -5, 0, 255, 0, 256], dtype = np.uint8)
/var/folders/_x/7v1hghg91r37__pjl_6c64sm0000gn/T/ipykernel_63757/795138074.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -5 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([-3, -5, 0, 255, 0, 256], dtype = np.uint8)
/var/folders/_x/7v1hghg91r37__pjl_6c64sm0000gn/T/ipykernel_63757/795138074.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers t

array([253, 251,   0, 255,   0,   0], dtype=uint8)

In [5]:
np.random.randint(0, 100, size = 10, dtype = np.int8)

array([74, 55, 79, 23, 44, 49, 95, 90, 21, 39], dtype=int8)

In [6]:
nd = np.random.rand(10, 2)
nd

array([[0.2757813 , 0.47691864],
       [0.71417155, 0.66245699],
       [0.83384285, 0.46247628],
       [0.56855874, 0.17372457],
       [0.21528038, 0.45103667],
       [0.64429546, 0.00565346],
       [0.19863621, 0.80975932],
       [0.22723715, 0.06717686],
       [0.64486205, 0.35701375],
       [0.13958971, 0.95044508]])

In [7]:
nd.dtype

dtype('float64')

In [8]:
# 产生一个新的数组; 原数组并没有改动
nd1 = np.asarray(nd, dtype ='float16')
nd1

array([[0.276   , 0.4768  ],
       [0.7144  , 0.6626  ],
       [0.834   , 0.4624  ],
       [0.5684  , 0.1737  ],
       [0.2153  , 0.451   ],
       [0.6445  , 0.005653],
       [0.1986  , 0.8096  ],
       [0.2273  , 0.0672  ],
       [0.645   , 0.357   ],
       [0.1396  , 0.9507  ]], dtype=float16)

In [9]:
display(nd.dtype, nd1.dtype)

dtype('float64')

dtype('float16')

In [11]:
nd1.astype(np.float16)

array([[0.276   , 0.4768  ],
       [0.7144  , 0.6626  ],
       [0.834   , 0.4624  ],
       [0.5684  , 0.1737  ],
       [0.2153  , 0.451   ],
       [0.6445  , 0.005653],
       [0.1986  , 0.8096  ],
       [0.2273  , 0.0672  ],
       [0.645   , 0.357   ],
       [0.1396  , 0.9507  ]], dtype=float16)

In [14]:
nd = np.random.randn(1000, 3)
np.save('./data1', nd)

In [15]:
np.load('./data1.npy')

array([[ 0.04248957, -0.36477885, -0.39131989],
       [-0.47329833, -0.74789648, -0.45657068],
       [-0.32298422, -0.42404448,  0.84834448],
       ...,
       [-0.04326044, -0.88903722,  1.21183632],
       [-1.1213152 , -1.49209325,  1.65734778],
       [ 0.62113259, -0.37587073,  1.44019925]])

In [16]:
np.save('./data2', nd.astype(np.float16))

In [17]:
np.load('./data2.npy')

array([[ 0.04248, -0.3647 , -0.3914 ],
       [-0.4734 , -0.748  , -0.4565 ],
       [-0.323  , -0.424  ,  0.848  ],
       ...,
       [-0.04327, -0.889  ,  1.212  ],
       [-1.121  , -1.492  ,  1.657  ],
       [ 0.621  , -0.376  ,  1.44   ]], dtype=float16)

In [21]:
# 字符串的数据类型
nd2 = np.array(list('abcdefghijklmn'))
nd2

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n'], dtype='<U1')

In [22]:
nd2.dtype

dtype('<U1')

### 2. 数据或者矩阵的计算

### 2.1 基本运算

In [25]:
nd1 = np.random.randint(1, 100, size = 5)
nd2 = np.random.randint(1, 10, size = 5)
display(nd1, nd2)

array([84, 10, 74, 99,  5])

array([7, 7, 1, 4, 2])

In [27]:
# 逐个元素相加
nd1 + nd2

array([ 91,  17,  75, 103,   7])

In [28]:
# 逐个元素相减
nd1 - nd2

array([77,  3, 73, 95,  3])

In [29]:
# 逐个元素相乘
nd1 * nd2

array([588,  70,  74, 396,  10])

In [30]:
# 逐个元素相除
nd1 / nd2

array([12.        ,  1.42857143, 74.        , 24.75      ,  2.5       ])

In [31]:
# 幂等运算
nd1 ** nd2

array([29509034655744,       10000000,             74,       96059601,
                   25])

In [39]:
# 幂等运算 power 函数, 内部传递两个参数
np.power(nd1, nd2)

array([29509034655744,       10000000,             74,       96059601,
                   25])

In [36]:
# 对数函数
np.log(10)

2.302585092994046

In [37]:
np.log10(1000)

3.0

In [38]:
np.log2(1024)

10.0

### 2.2 逻辑运算

In [40]:
display(nd1, nd2)

array([84, 10, 74, 99,  5])

array([7, 7, 1, 4, 2])

In [41]:
# 问一下 nd1 和 nd2 数组中每个对应的元素 是否都 > 呢
nd1 > nd2

array([ True,  True,  True,  True,  True])

In [42]:
nd1 < nd2

array([False, False, False, False, False])

In [43]:
nd1 >= nd2

array([ True,  True,  True,  True,  True])

In [44]:
nd1 == nd2

array([False, False, False, False, False])

### 2.3 数组和标量的计算

In [46]:
display(nd1, nd2)

array([84, 10, 74, 99,  5])

array([7, 7, 1, 4, 2])

In [48]:
# 数组中每个元素都 + 10
nd1 + 10

array([ 94,  20,  84, 109,  15])

In [49]:
# 数组中每个元素都 - 10
nd1 - 10

array([74,  0, 64, 89, -5])

In [51]:
# 数组中每个元素都 * 10
nd1 * 10

array([840, 100, 740, 990,  50])

In [53]:
# 数组中每个元素都 / 10
nd1 / 10

array([8.4, 1. , 7.4, 9.9, 0.5])

In [56]:
# 数组也可以做分母；0不能做分母, 否则报出错误 inf
2 / np.array([1, 2, 0, 5])

/var/folders/_x/7v1hghg91r37__pjl_6c64sm0000gn/T/ipykernel_63757/4214880691.py:2: RuntimeWarning: divide by zero encountered in divide
  2 / np.array([1, 2, 0, 5])


array([2. , 1. , inf, 0.4])

### 2.3 -= += *= 等操作; 这种操作直接改的原始数组；没有 /= 操作

In [64]:
display(nd1, nd2)

array([292,  70, 262, 337,  55])

array([7, 7, 1, 4, 2])

In [65]:
nd1 += 10
nd1

array([302,  80, 272, 347,  65])

In [66]:
nd1 -= 10
nd1

array([292,  70, 262, 337,  55])

In [67]:
nd1 *= 3
nd1 

array([ 876,  210,  786, 1011,  165])