## 通用函数

### 1. 单个元素 常用的函数

abs、sqrt、square、exp、log、sin、cos、tan、maxinmum、minimum、                                             
all、any、inner、clip、round、trace、ceil、floor

In [1]:
import numpy as np

a = np.array([-1, 3, 5, -2, 11, 10, -6], dtype=np.float16)
a

array([-1,  3,  5, -2, 11, 10, -6])

In [2]:
# 使用绝对值函数 abs
np.abs(a)

array([ 1,  3,  5,  2, 11, 10,  6])

In [6]:
# 使用开平方函数 (张量中不能有负数)
np.sqrt(a)

/var/folders/_x/7v1hghg91r37__pjl_6c64sm0000gn/T/ipykernel_74583/4111930249.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([       nan, 1.73205081, 2.23606798,        nan, 3.31662479,
       3.16227766,        nan])

In [7]:
# 使用 平方函数
np.square(a)

array([  1,   9,  25,   4, 121, 100,  36])

In [8]:
# exp 自然底数e 的多少次幂
np.exp(3)

20.085536923187668

In [9]:
np.e**3

20.085536923187664

In [10]:
# 求自然底数e的对数
np.log(20)

2.995732273553991

In [11]:
# 三角函数
np.sin(np.pi / 2)

1.0

In [13]:
np.cos(0)

1.0

In [14]:
np.tan(np.pi / 4)

0.9999999999999999

In [20]:
# 单个元素取最大
np.maximum(a[0], a[1])

array([12, 14, 14, 16, 16, 16, 15])

In [21]:
# 打印一下a 
a

array([-1,  3,  5, -2, 11, 10, -6])

In [22]:
c = np.random.randint(10, 17, size =7);
c
# 两个数组中 每个位置都选大的
np.maximum(a, c)

array([14, 10, 10, 11, 14, 15, 12])

In [25]:
# any 如果数据有一个不是 0 的就返回 True
nd1 = np.array([1, 3, 5, 0])
nd2 = np.array([-1, 13, 15, 10])
np.any(nd1) # True
np.any(nd2) # True

True

In [27]:
# all 只有所有数据都不是 0 才返回 True
np.all(nd1)  #False
np.all(nd2)  #True

True

In [28]:
# inner 返回的是两个数组的内积
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([1, 2, 3, 4, 5, 5])
np.inner(a, b)

85

In [33]:
# clip 有裁剪的意思; 
nd1 = np.random.randint(0, 100, size = 30)
nd1

np.clip(nd1, 20, 30) # <20的变为20; 大于30的变为30



array([30, 21, 30, 20, 30, 20, 30, 30, 30, 30, 30, 30, 30, 30, 27, 20, 27,
       30, 20, 30, 30, 30, 30, 20, 20, 20, 30, 30, 30, 20])

In [38]:
# round 保留小数的位数
nd1 = np.random.rand(10, 5)
nd1
nd1.round(2)

array([[0.85, 0.65, 0.91, 0.  , 0.97],
       [0.25, 0.3 , 0.92, 0.65, 0.95],
       [0.79, 0.49, 0.09, 0.87, 0.59],
       [0.96, 0.62, 0.41, 0.11, 0.9 ],
       [0.74, 0.99, 0.49, 0.92, 0.22],
       [0.79, 0.21, 0.35, 0.82, 0.1 ],
       [0.74, 0.69, 0.13, 0.37, 0.8 ],
       [0.26, 0.05, 0.09, 0.68, 0.7 ],
       [0.37, 0.68, 0.01, 0.25, 0.25],
       [0.82, 0.65, 0.04, 0.47, 0.66]])

In [40]:
# ceil 天花板；向上取整
np.ceil(np.array([-1.5, 2.7, 3.1, 4.5]))


array([-1.,  3.,  4.,  5.])

In [41]:
# floor 地板; 向下取整
np.floor(np.array([-1.5, 2.7, 3.1, 4.5]))

array([-2.,  2.,  3.,  4.])

In [42]:
a = np.random.randint(1, 10, size = (3, 5))
a

array([[5, 8, 9, 3, 2],
       [8, 3, 9, 8, 4],
       [5, 9, 4, 9, 5]])

In [45]:
# 求的是 坐标 i = j 的所有值的和; a[0][0] + a[1][1] + a[2][2]
np.trace(a)

12