## 张量相关

In [2]:
import torch

# 创建一个 5 * 3矩阵; 没有初始化的 张量
x = torch.empty(5 * 3)
print(x)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [3]:
# 创建一个 5 * 3的随机 张量
x = torch.rand(5 * 3)
print(x)

tensor([0.6812, 0.8772, 0.6047, 0.1293, 0.3209, 0.9989, 0.1444, 0.6112, 0.2815,
        0.6263, 0.2817, 0.0287, 0.1880, 0.8517, 0.8294])


In [5]:
# 创建一个数据类型为 long; 5 * 3 的张量
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
# 使用 tensors 现有数据 创建 张量
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [15]:
# 使用已经存在的张量 创建张量
x = x.new_ones(5, 3, dtype = torch.long)
print(x)

# 使用 like 系列
x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0.1280, 0.5491, 0.5300],
        [0.8899, 0.1066, 0.4009],
        [0.9140, 0.3334, 0.6823],
        [0.1813, 0.8235, 0.9581],
        [0.4873, 0.2390, 0.0612]])


In [16]:
# 看下 x.size() 通过提示 可以看出来是 function
print(x.size())

torch.Size([5, 3])


In [22]:
# 张量的 + 法
y = torch.rand(size = (5, 3), dtype = torch.float)
display(x, y)
print(x + y)

tensor([[0.1280, 0.5491, 0.5300],
        [0.8899, 0.1066, 0.4009],
        [0.9140, 0.3334, 0.6823],
        [0.1813, 0.8235, 0.9581],
        [0.4873, 0.2390, 0.0612]])

tensor([[0.1468, 0.7894, 0.7989],
        [0.9173, 0.2867, 0.1425],
        [0.4632, 0.5960, 0.1348],
        [0.9443, 0.3876, 0.0978],
        [0.8119, 0.7384, 0.7967]])

tensor([[0.2748, 1.3385, 1.3289],
        [1.8072, 0.3933, 0.5435],
        [1.3771, 0.9294, 0.8171],
        [1.1256, 1.2111, 1.0558],
        [1.2992, 0.9774, 0.8579]])


In [23]:
# 使用 torch.add 方法进行 +
print(torch.add(x, y))

tensor([[0.2748, 1.3385, 1.3289],
        [1.8072, 0.3933, 0.5435],
        [1.3771, 0.9294, 0.8171],
        [1.1256, 1.2111, 1.0558],
        [1.2992, 0.9774, 0.8579]])


In [27]:
# 使用 result 作为输出
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[0.2748, 1.3385, 1.3289],
        [1.8072, 0.3933, 0.5435],
        [1.3771, 0.9294, 0.8171],
        [1.1256, 1.2111, 1.0558],
        [1.2992, 0.9774, 0.8579]])


In [28]:
# 将 x 添加到 y 上; 改变y的值
y.add_(x)
print(x)
print(y)

tensor([[0.1280, 0.5491, 0.5300],
        [0.8899, 0.1066, 0.4009],
        [0.9140, 0.3334, 0.6823],
        [0.1813, 0.8235, 0.9581],
        [0.4873, 0.2390, 0.0612]])
tensor([[0.2748, 1.3385, 1.3289],
        [1.8072, 0.3933, 0.5435],
        [1.3771, 0.9294, 0.8171],
        [1.1256, 1.2111, 1.0558],
        [1.2992, 0.9774, 0.8579]])
