## 张量相关

### 1.开始

In [1]:
import torch

# 创建一个 5 * 3矩阵; 没有初始化的 张量
x = torch.empty(5 * 3)
print(x)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [2]:
# 创建一个 5 * 3的随机 张量
x = torch.rand(5 * 3)
print(x)

tensor([0.1708, 0.8452, 0.7055, 0.2033, 0.1035, 0.0090, 0.7339, 0.3233, 0.0581,
        0.7419, 0.1932, 0.0138, 0.7089, 0.4797, 0.5991])


In [3]:
# 创建一个数据类型为 long; 5 * 3 的张量
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
# 使用 tensors 现有数据 创建 张量
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
# 使用已经存在的张量 创建张量
x = x.new_ones(5, 3, dtype = torch.long)
print(x)

# 使用 like 系列
x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0.1707, 0.4741, 0.2140],
        [0.8043, 0.9296, 0.1979],
        [0.9835, 0.1572, 0.6632],
        [0.9825, 0.1306, 0.2058],
        [0.0979, 0.4617, 0.2430]])


In [6]:
# 看下 x.size() 通过提示 可以看出来是 function
print(x.size())

torch.Size([5, 3])


In [7]:
# 张量的 + 法
y = torch.rand(size = (5, 3), dtype = torch.float)
display(x, y)
print(x + y)

tensor([[0.1707, 0.4741, 0.2140],
        [0.8043, 0.9296, 0.1979],
        [0.9835, 0.1572, 0.6632],
        [0.9825, 0.1306, 0.2058],
        [0.0979, 0.4617, 0.2430]])

tensor([[0.5746, 0.8838, 0.8583],
        [0.7613, 0.4556, 0.4155],
        [0.1142, 0.0794, 0.4880],
        [0.7629, 0.6949, 0.7155],
        [0.2480, 0.4131, 0.2466]])

tensor([[0.7454, 1.3579, 1.0723],
        [1.5656, 1.3851, 0.6135],
        [1.0977, 0.2366, 1.1513],
        [1.7454, 0.8255, 0.9213],
        [0.3459, 0.8748, 0.4897]])


In [8]:
# 使用 torch.add 方法进行 +
print(torch.add(x, y))

tensor([[0.7454, 1.3579, 1.0723],
        [1.5656, 1.3851, 0.6135],
        [1.0977, 0.2366, 1.1513],
        [1.7454, 0.8255, 0.9213],
        [0.3459, 0.8748, 0.4897]])


In [9]:
# 使用 result 作为输出
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[0.7454, 1.3579, 1.0723],
        [1.5656, 1.3851, 0.6135],
        [1.0977, 0.2366, 1.1513],
        [1.7454, 0.8255, 0.9213],
        [0.3459, 0.8748, 0.4897]])


In [10]:
# 将 x 添加到 y 上; 改变y的值
y.add_(x)
print(x)
print(y)

tensor([[0.1707, 0.4741, 0.2140],
        [0.8043, 0.9296, 0.1979],
        [0.9835, 0.1572, 0.6632],
        [0.9825, 0.1306, 0.2058],
        [0.0979, 0.4617, 0.2430]])
tensor([[0.7454, 1.3579, 1.0723],
        [1.5656, 1.3851, 0.6135],
        [1.0977, 0.2366, 1.1513],
        [1.7454, 0.8255, 0.9213],
        [0.3459, 0.8748, 0.4897]])


In [11]:
# 分片的使用方法
print(x[:, 1])

tensor([0.4741, 0.9296, 0.1572, 0.1306, 0.4617])


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
# 这里的 -1, 表示不知道这个数不清楚; 让程序自己计算
z = y.view(-1, 8)
print(x, y, z)
print(x.size(), y.size(), z.size())

tensor([[ 0.5220, -0.2460, -0.9138,  0.6371],
        [ 0.6715,  0.5116, -0.7247,  0.6533],
        [-0.1059,  1.2896,  1.1152, -1.1394],
        [-2.0005, -1.3317, -1.4362, -0.1909]]) tensor([ 0.5220, -0.2460, -0.9138,  0.6371,  0.6715,  0.5116, -0.7247,  0.6533,
        -0.1059,  1.2896,  1.1152, -1.1394, -2.0005, -1.3317, -1.4362, -0.1909]) tensor([[ 0.5220, -0.2460, -0.9138,  0.6371,  0.6715,  0.5116, -0.7247,  0.6533],
        [-0.1059,  1.2896,  1.1152, -1.1394, -2.0005, -1.3317, -1.4362, -0.1909]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
# 生成只有一个元素的 一维张量
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.4486])
1.4486216306686401


### 2.numpy 转换

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
# 使用 numpy 产生的数组 和 原始a张量使用同一份数据; 张量 ---> 数组 的转化: 使用 a.numpy()
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
b[1] = 10
print(a)

tensor([ 1., 10.,  1.,  1.,  1.])


In [23]:
a.add_(1)
print(a)
print(b)

tensor([ 3., 12.,  3.,  3.,  3.])
[ 3. 12.  3.  3.  3.]


In [27]:
# numpy库 创建的数组 转换成 张量
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [29]:
# 所有张量的计算都是基于 CPU 的; 字符串张量 不支持 cuda 张量
torch.cuda.is_available()

False

In [31]:
torch.cuda.device_count()      # 可用 GPU 数量
torch.cuda.get_device_name(0)  # 第 0 张 GPU 的名称
torch.cuda.current_device()    # 当前默认 GPU 编号

0

In [36]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

x = torch.tensor([1.0])
y = torch.ones_like(x, device=device)  # 直接在 GPU 上创建
x = x.to(device)                       # 把 x 搬到 GPU
z = x + y
print(z)                     # tensor([2.], device='cuda:0')
print(z.to("cpu", torch.double))  # tensor([2.], dtype=torch.float64)

cpu
tensor([2.])
tensor([2.], dtype=torch.float64)
