## 张量相关

### 1.开始

In [54]:
import torch

# 创建一个 5 * 3矩阵; 没有初始化的 张量
x = torch.empty(5 * 3)
print(x)

tensor([1.5766e-19, 1.0256e-08, 4.2004e-05, 3.0785e+12, 6.9366e-07, 6.6767e-07,
        2.7150e-06, 1.2470e+16, 2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31,
        7.2708e+31, 5.0778e+31, 3.2608e-12])


In [55]:
# 创建一个 5 * 3的随机 张量
x = torch.rand(5 * 3)
print(x)

tensor([0.3736, 0.7003, 0.8176, 0.0945, 0.2607, 0.3991, 0.6365, 0.5045, 0.9401,
        0.0591, 0.6633, 0.6077, 0.5517, 0.1139, 0.4055])


In [56]:
# 创建一个数据类型为 long; 5 * 3 的张量
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [57]:
# 使用 tensors 现有数据 创建 张量
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [58]:
# 使用已经存在的张量 创建张量
x = x.new_ones(5, 3, dtype = torch.long)
print(x)

# 使用 like 系列
x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0.1933, 0.5404, 0.2020],
        [0.6275, 0.3159, 0.2636],
        [0.6572, 0.5915, 0.1102],
        [0.8264, 0.6282, 0.4053],
        [0.6127, 0.1589, 0.1303]])


In [59]:
# 看下 x.size() 通过提示 可以看出来是 function
print(x.size())

torch.Size([5, 3])


In [60]:
# 张量的 + 法
y = torch.rand(size = (5, 3), dtype = torch.float)
display(x, y)
print(x + y)

tensor([[0.1933, 0.5404, 0.2020],
        [0.6275, 0.3159, 0.2636],
        [0.6572, 0.5915, 0.1102],
        [0.8264, 0.6282, 0.4053],
        [0.6127, 0.1589, 0.1303]])

tensor([[0.9812, 0.8613, 0.3455],
        [0.0891, 0.8617, 0.1391],
        [0.4750, 0.2267, 0.4636],
        [0.8686, 0.3724, 0.6123],
        [0.8085, 0.4979, 0.7021]])

tensor([[1.1745, 1.4017, 0.5475],
        [0.7166, 1.1776, 0.4027],
        [1.1321, 0.8181, 0.5739],
        [1.6950, 1.0006, 1.0176],
        [1.4212, 0.6568, 0.8325]])


In [61]:
# 使用 torch.add 方法进行 +
print(torch.add(x, y))

tensor([[1.1745, 1.4017, 0.5475],
        [0.7166, 1.1776, 0.4027],
        [1.1321, 0.8181, 0.5739],
        [1.6950, 1.0006, 1.0176],
        [1.4212, 0.6568, 0.8325]])


In [62]:
# 使用 result 作为输出
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[1.1745, 1.4017, 0.5475],
        [0.7166, 1.1776, 0.4027],
        [1.1321, 0.8181, 0.5739],
        [1.6950, 1.0006, 1.0176],
        [1.4212, 0.6568, 0.8325]])


In [63]:
# 将 x 添加到 y 上; 改变y的值
y.add_(x)
print(x)
print(y)

tensor([[0.1933, 0.5404, 0.2020],
        [0.6275, 0.3159, 0.2636],
        [0.6572, 0.5915, 0.1102],
        [0.8264, 0.6282, 0.4053],
        [0.6127, 0.1589, 0.1303]])
tensor([[1.1745, 1.4017, 0.5475],
        [0.7166, 1.1776, 0.4027],
        [1.1321, 0.8181, 0.5739],
        [1.6950, 1.0006, 1.0176],
        [1.4212, 0.6568, 0.8325]])


In [64]:
# 分片的使用方法
print(x[:, 1])

tensor([0.5404, 0.3159, 0.5915, 0.6282, 0.1589])


In [65]:
x = torch.randn(4, 4)
y = x.view(16)
# 这里的 -1, 表示不知道这个数不清楚; 让程序自己计算
z = y.view(-1, 8)
print(x, y, z)
print(x.size(), y.size(), z.size())

tensor([[-0.6687, -1.1462, -1.6742,  1.1090],
        [ 0.7474,  0.8671,  1.5689,  1.2390],
        [ 0.7566, -0.0280,  0.4422, -1.1878],
        [-0.2751, -1.3827,  0.5178,  0.5044]]) tensor([-0.6687, -1.1462, -1.6742,  1.1090,  0.7474,  0.8671,  1.5689,  1.2390,
         0.7566, -0.0280,  0.4422, -1.1878, -0.2751, -1.3827,  0.5178,  0.5044]) tensor([[-0.6687, -1.1462, -1.6742,  1.1090,  0.7474,  0.8671,  1.5689,  1.2390],
        [ 0.7566, -0.0280,  0.4422, -1.1878, -0.2751, -1.3827,  0.5178,  0.5044]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [66]:
# 生成只有一个元素的 一维张量
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.3705])
-1.370498776435852


### 2.numpy 转换

In [67]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [68]:
# 使用 numpy 产生的数组 和 原始a张量使用同一份数据; 张量 ---> 数组 的转化: 使用 a.numpy()
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [69]:
b[1] = 10
print(a)

tensor([ 1., 10.,  1.,  1.,  1.])


In [70]:
a.add_(1)
print(a)
print(b)

tensor([ 2., 11.,  2.,  2.,  2.])
[ 2. 11.  2.  2.  2.]


In [71]:
# numpy库 创建的数组 转换成 张量
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [72]:
# 所有张量的计算都是基于 CPU 的; 字符串张量 不支持 cuda 张量
torch.cuda.is_available()

True

In [79]:
print(torch.cuda.device_count())      # 可用 GPU 数量
print(torch.cuda.get_device_name(0))  # 第 0 张 GPU 的名称
print(torch.cuda.current_device())    # 当前默认 GPU 编号

1
Tesla T4
0


In [80]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

x = torch.tensor([1.0])
y = torch.ones_like(x, device=device)  # 直接在 GPU 上创建
x = x.to(device)                       # 把 x 搬到 GPU
z = x + y
print(z)                     # tensor([2.], device='cuda:0')
print(z.to("cpu", torch.double))  # tensor([2.], dtype=torch.float64)

cuda
tensor([2.], device='cuda:0')
tensor([2.], dtype=torch.float64)
