## 自动求导和张量

### 1. 张量

In [1]:
import torch

# 创建一个张量, 开启张量的自动求导追踪
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
# 对张量 x 进行操作；
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [3]:
print(y.grad_fn)

In [4]:
# 对张量 y 再进行一个操作 
z = y * y * 3
out = z.mean()
print(z)
print(z.size)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
<built-in method size of Tensor object at 0x115d8ead0>
tensor(27., grad_fn=<MeanBackward0>)


In [5]:
# 可以手动对自动求导进行打开; 默认的是关闭的
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1) )
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


### 2.梯度

In [6]:
# 为了查看 梯度; 这块将 x,y,z,out 都打印出来看看
print(x)
x.retain_grad()
print(y)
y.retain_grad()
print(z)
z.retain_grad()
print(out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [7]:
# 使用 backward() 进行 反向传播
out.backward()

In [13]:
# 反向传播学习 backward()
x = torch.randint(1, 10, size = (3,), dtype = float)
print(x, x.requires_grad, x.is_leaf)

x.requires_grad_()
y = x * 2

while y.data.norm() > 1000:
    y = y * y * 2

y.retain_grad()

z = y * y * y * 3
z.retain_grad()

gradients = torch.tensor([1.0, 1.0, 1.0])
z.backward(gradients)

print('x = ' + str(x), 'x.grad = ' + str(x.grad))
print('y = ' + str(y), 'y.grad = ' + str(y.grad))
print('z = ' + str(z), 'z.grad = ' + str(z.grad))


tensor([4., 4., 9.], dtype=torch.float64) False True
x = tensor([4., 4., 9.], dtype=torch.float64, requires_grad=True) x.grad = tensor([1152., 1152., 5832.], dtype=torch.float64)
x = tensor([ 8.,  8., 18.], dtype=torch.float64, grad_fn=<MulBackward0>) y.grad = tensor([ 576.,  576., 2916.], dtype=torch.float64)
x = tensor([ 1536.,  1536., 17496.], dtype=torch.float64, grad_fn=<MulBackward0>) z.grad = tensor([1., 1., 1.], dtype=torch.float64)
