## 自动求导和张量

### 1. 张量

In [71]:
import torch

# 创建一个张量, 开启张量的自动求导追踪
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [72]:
# 对张量 x 进行操作；
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [73]:
print(y.grad_fn)

In [74]:
# 对张量 y 再进行一个操作 
z = y * y * 3
out = z.mean()
print(z)
print(z.size)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
<built-in method size of Tensor object at 0x00000176027F8D20>
tensor(27., grad_fn=<MeanBackward0>)


In [75]:
# 可以手动对自动求导进行打开; 默认的是关闭的
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1) )
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


### 2.梯度

In [76]:
# 为了查看 梯度; 这块将 x,y,z,out 都打印出来看看
print(x)
x.retain_grad()
print(y)
y.retain_grad()
print(z)
z.retain_grad()
print(out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [77]:
# 使用 backward() 进行 反向传播
out.backward()

In [79]:
# 只有叶子节点 的 grad 有值; 这个 grad 值; 是下一个函数对当前 张量的求导
print(x.grad)
print(y.grad)
print(z.grad)
print(out.grad)
# is_leaf 是叶子节点; grad_fn: 查看是不是不是 计算出来的
print(x.is_leaf)
print(y.grad_fn)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
None
True


C:\Users\jianwei.yang\AppData\Local\Temp\ipykernel_6504\3009410578.py:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:498.)
  print(out.grad)


In [63]:
print(x.dtype, y.dtype, z.dtype, out.dtype)

torch.float32 torch.float32 torch.float32 torch.float32


In [88]:
# 看一下个 雅可比矩阵的 案例
x = torch.randn(3, requires_grad = True)
print(x)

tensor([-0.3049, -1.3306, -0.2133], requires_grad=True)


In [94]:
y = x * 2
print(y)
print(y.data.norm())



tensor([-0.6098, -2.6613, -0.4267], grad_fn=<MulBackward0>)
tensor(2.7634)
